os:
  - linux
  - osx

dist: trusty
sudo: required
language: node_js
node_js:
  - "8"

before_install:
  - case "$TRAVIS_OS_NAME" in
    linux) sudo apt-get install -y bison flex libssl-dev libboost-dev libboost-system-dev libboost-filesystem-dev libboost-regex-dev ;;
    osx) brew install bison; brew link --force bison ;;
    esac

env:
  global:
    - NODE_ENV=development
